const KEY_BG_IMG = 'KEY_BG_IMG';
const KEY_CHAR_IMG = 'KEY_CHAR_IMG';
const KEY_SADFACE_CHAR_IMG = 'KEY_SADFACE_CHAR_IMG';
const KEY_HAPPYFACE_CHAR_IMG = 'KEY_HAPPYFACE_CHAR_IMG'
const KEY_CLOUD_IMG = 'KEY_CLOUD_IMG';
const KEY_ERASER_IMG = 'KEY_ERASER_IMG';
const KEY_HAND_IMG = 'KEY_HAND_IMG';
const KEY_BRUSH_IMG = 'KEY_BRUSH_IMG';
const KEY_ARROW_IMG = 'KEY_ARROW_IMG';
const KEY_TEXT_IMG = 'KEY_TEXT_IMG';
const KEY_TURORIAL_IMG = 'KEY_TURORIAL_IMG';
const KEY_LOGO_IMG = 'KEY_LOGO_IMG';

const KEY_BG_SOUND = 'KEY_BG_SOUND';
const KEY_WIN_SOUND = 'KEY_WIN_SOUND';
const KEY_ERASER_SOUND = 'KEY_ERASER_SOUND';